import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en-us">
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          httpEquiv="Content-Type"
          content="text/html; charset=UTF-8"
        />
        <meta name="referrer" content="always" />
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="Tra cứu, tìm kiếm, search, hỏi đáp, giải đáp, giải bài tập, tìm đáp án, luyện thi, giải bài tập, giải đề thi, giải đề kiểm tra"
        />
        <meta name="theme-color" content="#ffffff" />
        <link rel="icon" href="/android-icon-96x96.png" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
